const path = require('path');

// Regex patterns for invisible zero-width unicode characters
const ZERO_WIDTH_REGEX = /[\u200B\u200C\u200D\uFEFF\u00AD\u2060\u2061\u2062\u2063\u2064\u200E\u200F]/g;

// Regex patterns for Bidi control override security characters
const BIDI_REGEX = /[\u202A\u202B\u202C\u202D\u202E\u2066\u2067\u2068\u2069]/g;

// Regex patterns for LLM prompt markers and tokens
const PROMPT_TOKEN_REGEX = /<\|im_start\|>|<\|im_end\|>|\[INST\]|\[\/INST\]|<\|endoftext\|>|<\|endofpiece\|>|<\|system\|>|<\|user\|>|<\|assistant\|>/gi;

// Regex for non-standard whitespace characters (excluding standard \n \r \t)
const OBSCURE_SPACE_REGEX = /[\u00A0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000]/g;

// Regex patterns for AI attribution comments
const AI_COMMENT_SIGNATURES = [
  /auto-generated by ai/i,
  /generated by ai/i,
  /created by ai/i,
  /written by ai/i,
  /co-authored-by: ai/i,
  /ai-generated code/i,
  /ai generated/i,
  /ai watermark/i
];

function getCommentSyntax(ext) {
  const e = (ext || '').toLowerCase();
  if (['.py', '.rb', '.sh', '.bash', '.pl', '.r', '.yaml', '.yml', '.toml'].includes(e)) {
    return 'hash';
  }
  if (['.html', '.xml', '.svg', '.md'].includes(e)) {
    return 'xml';
  }
  if (['.css', '.scss', '.less'].includes(e)) {
    return 'c_block';
  }
  if (['.sql', '.lua'].includes(e)) {
    return 'dash';
  }
  return 'slash'; // default .js, .ts, .c, .cpp, .java, etc.
}

function cleanText(input, options = {}) {
  const opts = {
    stripZeroWidth: true,
    stripBidi: true,
    stripTokens: true,
    stripComments: true,
    normalizeQuotes: false,
    ext: '',
    ...options
  };

  let text = input;
  const stats = {
    zeroWidthCount: 0,
    bidiCount: 0,
    tokenCount: 0,
    spaceCount: 0,
    quoteCount: 0,
    commentCount: 0,
    changed: false
  };

  if (!text || typeof text !== 'string') {
    return { text: input, stats };
  }

  // 1. Strip zero-width unicode characters
  if (opts.stripZeroWidth) {
    const zwMatches = text.match(ZERO_WIDTH_REGEX);
    if (zwMatches) {
      stats.zeroWidthCount = zwMatches.length;
      text = text.replace(ZERO_WIDTH_REGEX, '');
    }
  }

  // 2. Strip Bidi override control characters
  if (opts.stripBidi) {
    const bidiMatches = text.match(BIDI_REGEX);
    if (bidiMatches) {
      stats.bidiCount = bidiMatches.length;
      text = text.replace(BIDI_REGEX, '');
    }
  }

  // 3. Strip LLM prompt tokens
  if (opts.stripTokens) {
    const tokenMatches = text.match(PROMPT_TOKEN_REGEX);
    if (tokenMatches) {
      stats.tokenCount = tokenMatches.length;
      text = text.replace(PROMPT_TOKEN_REGEX, '');
    }
  }

  // 4. Normalize obscure space characters
  const spaceMatches = text.match(OBSCURE_SPACE_REGEX);
  if (spaceMatches) {
    stats.spaceCount = spaceMatches.length;
    text = text.replace(OBSCURE_SPACE_REGEX, ' ');
  }

  // 5. Smart quote normalization
  if (opts.normalizeQuotes) {
    const smartQuoteRegex = /[“”‘’]/g;
    const quoteMatches = text.match(smartQuoteRegex);
    if (quoteMatches) {
      stats.quoteCount = quoteMatches.length;
      text = text
        .replace(/[“”]/g, '"')
        .replace(/[‘’]/g, "'");
    }
  }

  // 6. Language-aware AI comment stripping
  if (opts.stripComments) {
    const syntax = getCommentSyntax(opts.ext);
    const lines = text.split('\n');
    const cleanedLines = [];

    for (let line of lines) {
      const trimmed = line.trim();
      let isAiComment = false;

      // Check if line contains AI signature
      const containsAiSig = AI_COMMENT_SIGNATURES.some(sig => sig.test(line));

      if (containsAiSig) {
        if (syntax === 'slash' && (trimmed.startsWith('//') || trimmed.startsWith('/*'))) {
          isAiComment = true;
        } else if (syntax === 'hash' && trimmed.startsWith('#')) {
          isAiComment = true;
        } else if (syntax === 'xml' && trimmed.startsWith('<!--')) {
          isAiComment = true;
        } else if (syntax === 'dash' && trimmed.startsWith('--')) {
          isAiComment = true;
        } else if (syntax === 'c_block' && trimmed.startsWith('/*')) {
          isAiComment = true;
        }
      }

      if (isAiComment) {
        stats.commentCount++;
      } else {
        cleanedLines.push(line);
      }
    }

    text = cleanedLines.join('\n');
  }

  stats.changed = text !== input;
  return { text, stats };
}

module.exports = {
  cleanText,
  ZERO_WIDTH_REGEX,
  BIDI_REGEX,
  PROMPT_TOKEN_REGEX,
  OBSCURE_SPACE_REGEX
};
